#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER ${H2OAI_STORAGE_POSTGRES_USER} WITH ENCRYPTED PASSWORD '${H2OAI_STORAGE_POSTGRES_PASSWORD}';
    CREATE DATABASE ${H2OAI_STORAGE_POSTGRES_DB};
    GRANT ALL PRIVILEGES ON DATABASE ${H2OAI_STORAGE_POSTGRES_DB} TO ${H2OAI_STORAGE_POSTGRES_USER};
EOSQL
